## Two functions - one to create a special matrix object that can cache its inverse
## the second will compute the inverse of a matrix or fetch it from the cache when possible

## Takes a matrix as a parameter and converts it to a special matrix 
## that can cache its inverse - it returns a list

makeCacheMatrix <- function(x = matrix()) {
    m <- NULL
    set <- function(y) {
      x <<- y
      m <<- NULL
    }
    get <- function() x
    setinverse <- function(inv) m <<- inv
    getinverse <- function() m
    list(set = set, get = get,
         setinverse = setinverse,
         getinverse = getinverse)
}


## Takes a special matrix generated by the makeCacheMatrix function
## and will return the inverse of it by obtaining it from the cache
## if possible, otherwise computing the inverse and storing it in the
## cache to be used later

cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
        m <- x$getinverse()
        if(!is.null(m)){
          message("getting cached data")
          return(m)
        }
        data <-x$get()
        m <- solve(data)
        x$setinverse(m)
        m
}
